# Generated by Django 5.2.9 on 2026-04-10 12:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_aws_api_gateway_websockets', '0006_auto_20221215_0847'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionRateLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('attempt_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('successful', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connection_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'connection_rate_limits',
                'indexes': [models.Index(fields=['ip_address', 'attempt_time'], name='connection__ip_addr_636400_idx'), models.Index(fields=['user', 'attempt_time'], name='connection__user_id_fa2960_idx')],
            },
        ),
        migrations.CreateModel(
            name='WebSocketToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True, validators=[django.core.validators.RegexValidator('^[a-f0-9]{64}$', 'Invalid token format')])),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='websocket_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'websocket_tokens',
                'indexes': [models.Index(fields=['token', 'used'], name='websocket_t_token_b1045e_idx'), models.Index(fields=['created_at'], name='websocket_t_created_c55db3_idx')],
            },
        ),
    ]
