# Generated by Django 5.2.9 on 2026-05-28 11:42

from django.db import migrations, models


class RemoveIndexIfExists(migrations.RemoveIndex):
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = from_state.apps.get_model(app_label, self.model_name)
        table_name = model._meta.db_table

        with schema_editor.connection.cursor() as cursor:
            constraints = schema_editor.connection.introspection.get_constraints(
                cursor,
                table_name,
            )

        if self.name not in constraints:
            return

        super().database_forwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):

    dependencies = [
        (
            "django_aws_api_gateway_websockets",
            "0007_connectionratelimit_websockettoken",
        ),
    ]

    operations = [
        RemoveIndexIfExists(
            model_name="websockettoken",
            name="websocket_t_token_b1045e_idx",
        ),
        migrations.AddIndex(
            model_name="websockettoken",
            index=models.Index(
                fields=["token", "used"],
                name="idx_websocket_tokens_used",
            ),
        ),
    ]
