# Generated by Django 5.2.9 on 2026-05-28 11:42

from django.db import migrations, models


class RemoveIndexIfExists(migrations.RemoveIndex):
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = from_state.apps.get_model(app_label, self.model_name)
        table_name = model._meta.db_table

        with schema_editor.connection.cursor() as cursor:
            constraints = schema_editor.connection.introspection.get_constraints(
                cursor,
                table_name,
            )

        if self.name not in constraints:
            return

        try:
            super().database_forwards(app_label, schema_editor, from_state, to_state)
        except Exception:
            pass


class Migration(migrations.Migration):

    dependencies = [
        (
            "django_aws_api_gateway_websockets",
            "0007_connectionratelimit_websockettoken",
        ),
    ]

    operations = [
        migrations.AlterModelTable(
            name="connectionratelimit",
            table="django_aws_api_gateway_websockets_connectionratelimit",
        ),
        migrations.AlterModelTable(
            name="websockettoken",
            table="django_aws_api_gateway_websockets_websockettoken",
        ),
        RemoveIndexIfExists(
            model_name="websockettoken",
            name="websocket_t_token_b1045e_idx",
        ),
        RemoveIndexIfExists(
            model_name="connectionratelimit",
            name="connection__ip_addr_636400_idx",
        ),
        RemoveIndexIfExists(
            model_name="connectionratelimit",
            name="connection__user_id_fa2960_idx",
        ),
        migrations.AddIndex(
            model_name="connectionratelimit",
            index=models.Index(
                fields=["ip_address", "attempt_time"],
                name="idx_ip_attempt_time",
            ),
        ),
        migrations.AddIndex(
            model_name="connectionratelimit",
            index=models.Index(
                fields=["user", "attempt_time"],
                name="idx_user_attempt_time",
            ),
        ),
        migrations.AddIndex(
            model_name="websockettoken",
            index=models.Index(
                fields=["token", "used"],
                name="idx_websocket_tokens_used",
            ),
        ),
    ]
