# Generated by Django 5.2.9 on 2026-05-28 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "django_aws_api_gateway_websockets",
            "0008_remove_websockettoken_websocket_t_created_c55db3_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelTable(
            name="connectionratelimit",
            table=None,
        ),
        migrations.AlterModelTable(
            name="websockettoken",
            table=None,
        ),
    ]
