repos:
- repo: https://github.com/psf/black
  rev: 21.10b0
  hooks:
  - id: black
- repo: https://github.com/asottile/blacken-docs
  rev: v1.11.0
  hooks:
  - id: blacken-docs
    additional_dependencies:
    - black==21.9b0

# Turning off as it may well break the worker files
- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
  - id: isort
    args: ["--profile", "black", "--filter-files"]
